name = "backend"
type = "javascript"
zone_id = ""
account_id = "870d596bc7edb180166ec010bbc13185"
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
